# Generated by Django 5.0 on 2023-12-30 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='music_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='media/music/')),
                ('music_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.music')),
            ],
        ),
    ]
