# Generated by Django 5.0 on 2023-12-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_music_audio_file_music_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_file',
            name='music_key',
        ),
        migrations.DeleteModel(
            name='music',
        ),
        migrations.DeleteModel(
            name='music_file',
        ),
    ]
