# Generated by Django 5.0 on 2023-12-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='media/site/')),
                ('sample', models.FileField(null=True, upload_to='media/sample/')),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
