# Generated by Django 5.0 on 2024-01-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='inbox',
        ),
    ]
