# Generated by Django 5.0 on 2024-01-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_music_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_file',
        ),
    ]
